#!/usr/bin/env zsh

source_dir=${0:A:h}

export MARCCUP_autotest_DIR=${source_dir}/autotest

function push_pythonpath() {
	pth=$1:A
	echo "+ ${pth}"
	export PATH=${pth}/script:$PATH
	export PYTHONPATH=${pth}/package:$PYTHONPATH
}

push_pythonpath ${source_dir}/../oaktree
push_pythonpath ${source_dir}/../cc_pathlib
push_pythonpath ${source_dir}

export MARCCUP_static_DIR=${source_dir}/static
export MARCCUP_repo_DIR="/mnt/workbench/source/marccup/test/parser/book"

typeset -T PYTHONPATH pythonpath

typeset -U pythonpath
typeset -U path
