#!/usr/bin/env zsh

source_DIR=$0:A:h

function push_pythonpath() {
	pth=$1:A
	echo "+ ${pth}"
	export PATH=${pth}/script:$PATH
	export PYTHONPATH=${pth}/package:$PYTHONPATH
}

push_pythonpath ${source_DIR}/../oaktree
push_pythonpath "${source_DIR}/../cc-pathlib"
push_pythonpath ${source_DIR}

export MARCCUP_static_DIR=${source_DIR}/static
export MARCCUP_repo_DIR="/mnt/workbench/source/marccup/test/parser/book"

typeset -T PYTHONPATH pythonpath

typeset -U pythonpath
typeset -U path
